[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_security_token = "6yEnqdEjX3zBBDkzhwTRGJwv1jRaN4QE4gywmgdcfPBZ"
security_transfer_hook = "4yEnqdEjX3zBBDkzhwTRGJwv1jRaN4QE4gywmgdcfPBZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/solana-security-token",
  "programs/security-transfer-hook",
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
