name: Test

on: [push]

jobs:
  Test:
    runs-on: [ubuntu-22.04]
    env:
      RUST_VERSION: 1.78.0
      SOLANA_VERSION: 1.18.17
      ANCHOR_VERSION: 0.30.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy

      - name: Install Solana
        uses: metadaoproject/setup-solana@v1.0
        with: 
          solana-cli-version: ${{ env.SOLANA_VERSION }}
      
      - name: Generate Key
        run: solana-keygen new --no-passphrase

      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked

      - name: Build
        run: anchor build

      - name: Install Dependencies
        run: yarn install

      - name: JS E2E Tests
        run: anchor test

      - name: Install llvm-cov
        run: cargo install cargo-llvm-cov
      
      - name: Rust Tests
        run: cargo llvm-cov